#################################################################################
##                      _   _               ____   ____                        ##
##____________________ | \ | |  ___   ___  | __ ) | __ )  _____________________##
##____________________ |  \| | / _ \ / _ \ |  _ \ |  _ \  _____________________##
##____________________ | |\  ||  __/| (_) || |_) || |_) | _____________________##
##____________________ |_| \_| \___| \___/ |____/ |____/  _____________________##
##                                Configuration                                ##
##                                                                             ##
##      WEBSITE:       https://hectus.net/neobb                                ##
##      SOURCE-CODE:   https://github.com/HectusNet/NeoBlockBattles            ##
##      BUGS & ISSUES: https://github.com/HectusNet/NeoBlockBattles/issues     ##
##                                                                             ##
#################################################################################


## The method of storing and loading structures. ##
#   Available Methods:
#     | -> server  : fetch from the global database
#     | -> local   : in the plugin folder
#     | -> global  : at '~/.config/neobb-structures' on your system
# Default: server
structure-mode: false


## The maximum arena height. ##
# Keep in mind that higher values will require much more RAM.
# Default: 9
max-arena-height: 9


## The database configuration. ##
# Only recommended for actual server networks.
# Disabled by default
database:

  # If all userdata should be stored in a PostgreSQL database.
  enabled: false

  # The address/ip of the database. Can be localhost.
  address: localhost

  # The port of the database. If set to 0, will use the database's default port.
  port: 0

  # The name of the database.
  database: database_name

  # The table of the database to use.
  table: table_name

  # The database login credentials.
  user: username
  passwd: password
