#################################################################################
##                      _   _               ____   ____                        ##
##____________________ | \ | |  ___   ___  | __ ) | __ )  _____________________##
##____________________ |  \| | / _ \ / _ \ |  _ \ |  _ \  _____________________##
##____________________ | |\  ||  __/| (_) || |_) || |_) | _____________________##
##____________________ |_| \_| \___| \___/ |____/ |____/  _____________________##
##                                Configuration                                ##
##                                                                             ##
##      WEBSITE:       https://hectus.net/neobb                                ##
##      SOURCE-CODE:   https://github.com/HectusNet/NeoBlockBattles            ##
##      BUGS & ISSUES: https://github.com/HectusNet/NeoBlockBattles/issues     ##
##                                                                             ##
#################################################################################


## The method of storing and loading structures. ##
#   Available Methods:
#     | -> server  : fetch from the global database
#     | -> local   : in the plugin folder
#     | -> global  : at '~/.config/neobb-structures' on your system
# Default: server
structure-mode: server


## The maximum arena height. ##
# Keep in mind that higher values will require much more RAM.
# Default: 9
max-arena-height: 9


## At how many players a game will start. ##
# This will only count players which are in adventure mode and have an empty inventory.
# Default: 2
starting-players: 2


## The database configuration. ##
# Only recommended for actual server networks.
# Disabled by default
database:

  # If all userdata should be stored in a PostgreSQL database.
  enabled: false

  # The address/ip of the database. Can be localhost.
  address: localhost

  # The port of the database. If set to 0, will use the database's default port.
  port: 5432

  # The name of the database.
  database: database_name

  # The table of the database to use.
  table: table_name

  # The database login credentials.
  user: username
  passwd: password

## The warp location on the map. ##
# The default values assume the Hectus edition of the map
# and are likely not applicable to your own server.
warps:
  default: [ -276, 59, 148 ]
  amethyst: [ -341, 62, 324 ]
  cliff: [ 7, 30, 180 ]
  desert: [ -54, 8, 520 ]
  end: [ -17, 29, 19 ]
  frozen: [ -354, 13, 249 ]
  meadow: [ 0, 0, 0 ] # TODO: Build this!
  mushroom: [ -306, 16, 28 ]
  nerd: [ -387, 22, 472 ]
  nether: [ -199, 19, 146 ]
  ocean: [ -82, 22, 186 ]
  redstone: [ -178, 33, 349 ]
  sun: [ -345, 13, 148 ]
  void: [ -134, 22, 306 ]
  wood: [ -221, 22, 473 ]
