# Will store all structure files at ~/.config/neobb-structures/ instead of the plugin directory.
# Will only work on Linux systems!
global-structures: false

# Database-related configuration:
database:

  # Sets whether to try to connect to the database or just use no database.
  enabled: false

  # The address of the database. Should follow "jdbc:postgresql://[ADDRESS]:[PORT]/[DATABASE]".
  address: "jdbc:postgresql://localhost:5432/hectus"

  # The name of the table of the database to use.
  table: "neobb_playerdata"

  # The credentials to log into the database. The account should not have more permissions than it needs!
  username: "neobb_plugin"
  password: "Ye8ZfAZ6DohcuC"

# Warp/Map locations (centers):
warps:
  default: [ 0, 0, 0 ]
  nether: [ 0, 0, 0 ]
  end: [ 0, 0, 0 ]
  ocean: [ 0, 0, 0 ]
  frozen: [ 0, 0, 0 ]
  mushroom: [ 0, 0, 0 ]
  cliff: [ 0, 0, 0 ]
  meadow: [ 0, 0, 0 ]
  void: [ 0, 0, 0 ]
  redstone: [ 0, 0, 0 ]
  wood: [ 0, 0, 0 ]
  desert: [ 0, 0, 0 ]
  nerd: [ 0, 0, 0 ]
  amethyst: [ 0, 0, 0 ]
  sun: [ 0, 0, 0 ]
