#################################################################################
##                      _   _               ____   ____                        ##
##____________________ | \ | |  ___   ___  | __ ) | __ )  _____________________##
##____________________ |  \| | / _ \ / _ \ |  _ \ |  _ \  _____________________##
##____________________ | |\  ||  __/| (_) || |_) || |_) | _____________________##
##____________________ |_| \_| \___| \___/ |____/ |____/  _____________________##
##                                Configuration                                ##
##                                                                             ##
##          WEBSITE:       https://hectus.net/neobb                            ##
##          SOURCE-CODE:   https://github.com/HectusNet/NeoBB                  ##
##          BUGS & ISSUES: https://github.com/HectusNet/NeoBB/issues           ##
##                                                                             ##
#################################################################################


## If all online features should be disabled. ##
# This primarily includes translations and the database.
# Default: false
offline: true


## The method of storing and loading structures. ##
#   Available Methods:
#     | -> local   : in the plugin folder
#     | -> global  : at '~/.config/neobb-structures' on your system
#     | -> server  : fetch from the global database
# Default: server
structure-mode: local


## The maximum arena height. ##
# Keep in mind that higher values will require much more RAM.
# Default: 9
max-arena-height: 9


## Restart after Game ##
# Whether to restart the server after a game ends or not.
# Might interfere with the queue system, as this does not care
# if another game is running while said game ends.
restart-after-game: false


# An ordered list of commands to execute after a game ended.
# This, unlike `queue.pre-commands` and `queue.post-commands`, will execute even if the queue is disabled.
#   Available Placeholders:
#     | -> '{id}'       : started game's ID
#     | -> '{mode}'     : started game's game-mode
#     | -> '{players}'  : amount of players in the started game
#     | -> '{world}'    : name of the game's world
#     | -> '{forced}'   : "true" if forced (via `/game stop` or stopping server), "false" otherwise
#     | -> '{winner}'   : the winner's name, or "null" if it's a draw
ending-commands:
  - "/say Ending game... ({winner} won)" # <- example, you can freely remove this and leave the list empty.


## Respawn at Config ##
# Whether to respawn players at the configured `player-spawn` below instead of making them spectate.
# If spectating (=false), it will spawn players in spectator mode in the middle of the game.
# Default: false
respawn-at-config: false


## Player Spawn ##
# Where and how to spawn players after the game ends.
# If above value is set to true, players will also spawn here when dying.
player-spawn:

  # The game mode to set players to when spawning here.
  game-mode: adventure

  # The world to spawn in. The default world is called "world".
  world: world

  # The location to spawn the player at.
  # If the y-component is set to -64.0, the player will spawn at the world spawn.
  location: [ 0.0, -64.0, 0.0 ]


## Queue ##
# The optional queue module for automatically starting games when enough players joined.
queue:

  # Whether the queue module is enabled or not.
  enabled: false

  # The minimum amount of players needed to start a game.
  min-players: 2

  # The maximum amount of players before splitting the queue.
  max-players: 5

  # The interval in seconds between checking if the amount of player is valid and starting a game.
  # Set to -1 to start instantly as soon as `min-players` queued.
  check-interval: 15

  # How players enter or leave the queue.
  #   Available Methods:
  #     | -> command  : use '/queue' to enter the queue
  #     | -> auto     : anyone not in a game is automatically in the queue
  method: command

  # The game mode to use when starting a new game using the queue.
  #   Available Modes:
  #     | -> default  : the default NeoBB ruleset
  #     | -> card     : very boring, similar to a card game
  #     | -> person   : imbalanced, like Person98's remake in 2023
  mode: default

  # The difficulty to set when starting a new game using the queue.
  #   Available Difficulties:
  #     | -> easy   : no ranking, no rules, and more time
  #     | -> normal : normal settings
  #     | -> hard   : no suggestions, full rules, and less time
  #     | -> champ  : like hard, but even less time
  difficulty: normal

  # The world to start the game in.
  #   Available Placeholders:
  #     | -> '{id}'       : started game's ID
  #     | -> '{mode}'     : started game's game-mode
  #     | -> '{players}'  : amount of players in the started game
  world: "game-{id}"

  # An ordered list of commands to execute before any world or location is accessed.
  # This should only really be used to create a world for the game when using another plugin like MultiVerse.
  #   Available Placeholders:
  #     | -> '{id}'       : started game's ID
  #     | -> '{mode}'     : started game's game-mode
  #     | -> '{players}'  : amount of players in the started game
  pre-commands:
    - "/say Initializing game with {players} players..." # <- example, you can freely remove this and leave the list empty.

  # An ordered list of commands to execute after the world and location of the game were accessed.
  # Things like creating a world for the game cannot happen here anymore.
  #   Available Placeholders:
  #     | -> '{id}'       : started game's ID
  #     | -> '{mode}'     : started game's game-mode
  #     | -> '{players}'  : amount of players in the started game
  #     | -> '{world}'    : name of the game's world
  post-commands:
    - "/say Starting game at {x}/{y}/{z}..." # <- example, you can freely remove this and leave the list empty.


## The database configuration. ##
# Only recommended for actual server networks.
# Disabled by default
database:

  # If all userdata should be stored in a PostgreSQL database.
  enabled: false

  # The address/ip of the database. Can be `localhost`.
  address: localhost

  # The port of the database. If set to 0, it will use the database's default port.
  port: 0

  # The name of the database.
  database: database_name

  # The table of the database to use.
  table: table_name

  # The database login credentials.
  user: username
  passwd: password


## The warp cord on the map. ##
# The default values assume the Hectus edition of the map
# and are likely not applicable to your own server.
warps:
  default: [ -280, 59, 144 ]
  amethyst: [ -345, 62, 320 ]
  cliff: [ 3, 30, 176 ]
  desert: [ -58, 8, 516 ]
  end: [ -21, 29, 15 ]
  frozen: [ -358, 13, 245 ]
  meadow: [ 0, 0, 0 ] # TODO: Build this!
  mushroom: [ -310, 16, 24 ]
  nerd: [ -391, 22, 468 ]
  nether: [ -203, 19, 142 ]
  ocean: [ -86, 22, 182 ]
  redstone: [ -182, 33, 345 ]
  sun: [ -349, 13, 144 ]
  void: [ -138, 22, 302 ]
  wood: [ -225, 22, 469 ]

  person_amethyst: [ -345, 62, 320 ] # TODO: Build this!
  person_fire: [ -203, 19, 142 ] # TODO: Build this!
  person_ice: [ -358, 13, 245 ] # TODO: Build this!
  person_snow: [ -358, 13, 245 ] # TODO: Build this!
  person_villager: [ 0, 0, 0 ] # TODO: Build this!
  person_void: [ -138, 22, 302 ] # TODO: Build this!


# Disable FastStats Integration #
# FastStats sends completely anonymous data about the server's Minecraft version, used game modes, etc.
# to improve the plugin based on real usage data.
# If you do not want to send this data, feel free to opt out here, in FastStats' own configuration,
# or using the `-Dfaststats.enabled=false` JVM flag to disable FastStats globally.
disable-faststats: false


## The Configuration Version ##
# DO NOT MODIFY THIS, OR THE CONFIGURATION WILL LIKELY BREAK OR BE RESET!
version: 3
