#################################################################################
##                      _   _               ____   ____                        ##
##____________________ | \ | |  ___   ___  | __ ) | __ )  _____________________##
##____________________ |  \| | / _ \ / _ \ |  _ \ |  _ \  _____________________##
##____________________ | |\  ||  __/| (_) || |_) || |_) | _____________________##
##____________________ |_| \_| \___| \___/ |____/ |____/  _____________________##
##                                Configuration                                ##
##                                                                             ##
##          WEBSITE:       https://hectus.net/neobb                            ##
##          SOURCE-CODE:   https://github.com/HectusNet/NeoBB                  ##
##          BUGS & ISSUES: https://github.com/HectusNet/NeoBB/issues           ##
##                                                                             ##
#################################################################################


## If all online features should be disabled. ##
# This primarily includes translations and the database.
# Default: false
offline: true


## The method of storing and loading structures. ##
#   Available Methods:
#     | -> local   : in the plugin folder
#     | -> global  : at '~/.config/neobb-structures' on your system
#     | -> server  : fetch from the global database
# Default: server
structure-mode: local


## The maximum arena height. ##
# Keep in mind that higher values will require much more RAM.
# Default: 9
max-arena-height: 9


## Production Mode ##
# If this is set to true, the plugin will be loaded in production mode.
# Production mode will start a game based on the "starting-players" and restart the
# server once the current game ends. This is only useful for full-scale servers.
production: false


## At how many players a game will start. ##
# This will only count players which are in adventure mode and have an empty inventory.
# Default: 2
starting-players: 2


## The database configuration. ##
# Only recommended for actual server networks.
# Disabled by default
database:

  # If all userdata should be stored in a PostgreSQL database.
  enabled: false

  # The address/ip of the database. Can be `localhost`.
  address: localhost

  # The port of the database. If set to 0, it will use the database's default port.
  port: 5432

  # The name of the database.
  database: database_name

  # The table of the database to use.
  table: table_name

  # The database login credentials.
  user: username
  passwd: password


## The warp cord on the map. ##
# The default values assume the Hectus edition of the map
# and are likely not applicable to your own server.
warps:
  default: [ -280, 59, 144 ]
  amethyst: [ -345, 62, 320 ]
  cliff: [ 3, 30, 176 ]
  desert: [ -58, 8, 516 ]
  end: [ -21, 29, 15 ]
  frozen: [ -358, 13, 245 ]
  meadow: [ 0, 0, 0 ] # TODO: Build this!
  mushroom: [ -310, 16, 24 ]
  nerd: [ -391, 22, 468 ]
  nether: [ -203, 19, 142 ]
  ocean: [ -86, 22, 182 ]
  redstone: [ -182, 33, 345 ]
  sun: [ -349, 13, 144 ]
  void: [ -138, 22, 302 ]
  wood: [ -225, 22, 469 ]

  person-amethyst: [ -345, 62, 320 ] # TODO: Build this!
  person-fire: [ -203, 19, 142 ] # TODO: Build this!
  person-ice: [ -358, 13, 245 ] # TODO: Build this!
  person-snow: [ -358, 13, 245 ] # TODO: Build this!
  person-villager: [ 0, 0, 0 ] # TODO: Build this!
  person-void: [ -138, 22, 302 ] # TODO: Build this!
